// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOService.proto

package org.opendedup.grpc;

/**
 * Protobuf type {@code org.opendedup.grpc.CopyExtentRequest}
 */
public  final class CopyExtentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opendedup.grpc.CopyExtentRequest)
    CopyExtentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CopyExtentRequest.newBuilder() to construct.
  private CopyExtentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CopyExtentRequest() {
    srcFile_ = "";
    dstFile_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CopyExtentRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CopyExtentRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            srcFile_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dstFile_ = s;
            break;
          }
          case 24: {

            srcStart_ = input.readInt64();
            break;
          }
          case 32: {

            dstStart_ = input.readInt64();
            break;
          }
          case 40: {

            length_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opendedup.grpc.IOService.internal_static_org_opendedup_grpc_CopyExtentRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opendedup.grpc.IOService.internal_static_org_opendedup_grpc_CopyExtentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opendedup.grpc.CopyExtentRequest.class, org.opendedup.grpc.CopyExtentRequest.Builder.class);
  }

  public static final int SRCFILE_FIELD_NUMBER = 1;
  private volatile java.lang.Object srcFile_;
  /**
   * <code>string srcFile = 1;</code>
   * @return The srcFile.
   */
  public java.lang.String getSrcFile() {
    java.lang.Object ref = srcFile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      srcFile_ = s;
      return s;
    }
  }
  /**
   * <code>string srcFile = 1;</code>
   * @return The bytes for srcFile.
   */
  public com.google.protobuf.ByteString
      getSrcFileBytes() {
    java.lang.Object ref = srcFile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      srcFile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DSTFILE_FIELD_NUMBER = 2;
  private volatile java.lang.Object dstFile_;
  /**
   * <code>string dstFile = 2;</code>
   * @return The dstFile.
   */
  public java.lang.String getDstFile() {
    java.lang.Object ref = dstFile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dstFile_ = s;
      return s;
    }
  }
  /**
   * <code>string dstFile = 2;</code>
   * @return The bytes for dstFile.
   */
  public com.google.protobuf.ByteString
      getDstFileBytes() {
    java.lang.Object ref = dstFile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dstFile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRCSTART_FIELD_NUMBER = 3;
  private long srcStart_;
  /**
   * <code>int64 srcStart = 3;</code>
   * @return The srcStart.
   */
  public long getSrcStart() {
    return srcStart_;
  }

  public static final int DSTSTART_FIELD_NUMBER = 4;
  private long dstStart_;
  /**
   * <code>int64 dstStart = 4;</code>
   * @return The dstStart.
   */
  public long getDstStart() {
    return dstStart_;
  }

  public static final int LENGTH_FIELD_NUMBER = 5;
  private long length_;
  /**
   * <code>int64 length = 5;</code>
   * @return The length.
   */
  public long getLength() {
    return length_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSrcFileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, srcFile_);
    }
    if (!getDstFileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dstFile_);
    }
    if (srcStart_ != 0L) {
      output.writeInt64(3, srcStart_);
    }
    if (dstStart_ != 0L) {
      output.writeInt64(4, dstStart_);
    }
    if (length_ != 0L) {
      output.writeInt64(5, length_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSrcFileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, srcFile_);
    }
    if (!getDstFileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dstFile_);
    }
    if (srcStart_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, srcStart_);
    }
    if (dstStart_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, dstStart_);
    }
    if (length_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, length_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opendedup.grpc.CopyExtentRequest)) {
      return super.equals(obj);
    }
    org.opendedup.grpc.CopyExtentRequest other = (org.opendedup.grpc.CopyExtentRequest) obj;

    if (!getSrcFile()
        .equals(other.getSrcFile())) return false;
    if (!getDstFile()
        .equals(other.getDstFile())) return false;
    if (getSrcStart()
        != other.getSrcStart()) return false;
    if (getDstStart()
        != other.getDstStart()) return false;
    if (getLength()
        != other.getLength()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SRCFILE_FIELD_NUMBER;
    hash = (53 * hash) + getSrcFile().hashCode();
    hash = (37 * hash) + DSTFILE_FIELD_NUMBER;
    hash = (53 * hash) + getDstFile().hashCode();
    hash = (37 * hash) + SRCSTART_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSrcStart());
    hash = (37 * hash) + DSTSTART_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDstStart());
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLength());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opendedup.grpc.CopyExtentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.CopyExtentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opendedup.grpc.CopyExtentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opendedup.grpc.CopyExtentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opendedup.grpc.CopyExtentRequest)
      org.opendedup.grpc.CopyExtentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opendedup.grpc.IOService.internal_static_org_opendedup_grpc_CopyExtentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opendedup.grpc.IOService.internal_static_org_opendedup_grpc_CopyExtentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opendedup.grpc.CopyExtentRequest.class, org.opendedup.grpc.CopyExtentRequest.Builder.class);
    }

    // Construct using org.opendedup.grpc.CopyExtentRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      srcFile_ = "";

      dstFile_ = "";

      srcStart_ = 0L;

      dstStart_ = 0L;

      length_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opendedup.grpc.IOService.internal_static_org_opendedup_grpc_CopyExtentRequest_descriptor;
    }

    @java.lang.Override
    public org.opendedup.grpc.CopyExtentRequest getDefaultInstanceForType() {
      return org.opendedup.grpc.CopyExtentRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.opendedup.grpc.CopyExtentRequest build() {
      org.opendedup.grpc.CopyExtentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opendedup.grpc.CopyExtentRequest buildPartial() {
      org.opendedup.grpc.CopyExtentRequest result = new org.opendedup.grpc.CopyExtentRequest(this);
      result.srcFile_ = srcFile_;
      result.dstFile_ = dstFile_;
      result.srcStart_ = srcStart_;
      result.dstStart_ = dstStart_;
      result.length_ = length_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opendedup.grpc.CopyExtentRequest) {
        return mergeFrom((org.opendedup.grpc.CopyExtentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opendedup.grpc.CopyExtentRequest other) {
      if (other == org.opendedup.grpc.CopyExtentRequest.getDefaultInstance()) return this;
      if (!other.getSrcFile().isEmpty()) {
        srcFile_ = other.srcFile_;
        onChanged();
      }
      if (!other.getDstFile().isEmpty()) {
        dstFile_ = other.dstFile_;
        onChanged();
      }
      if (other.getSrcStart() != 0L) {
        setSrcStart(other.getSrcStart());
      }
      if (other.getDstStart() != 0L) {
        setDstStart(other.getDstStart());
      }
      if (other.getLength() != 0L) {
        setLength(other.getLength());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.opendedup.grpc.CopyExtentRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.opendedup.grpc.CopyExtentRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object srcFile_ = "";
    /**
     * <code>string srcFile = 1;</code>
     * @return The srcFile.
     */
    public java.lang.String getSrcFile() {
      java.lang.Object ref = srcFile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcFile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string srcFile = 1;</code>
     * @return The bytes for srcFile.
     */
    public com.google.protobuf.ByteString
        getSrcFileBytes() {
      java.lang.Object ref = srcFile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string srcFile = 1;</code>
     * @param value The srcFile to set.
     * @return This builder for chaining.
     */
    public Builder setSrcFile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      srcFile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string srcFile = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcFile() {
      
      srcFile_ = getDefaultInstance().getSrcFile();
      onChanged();
      return this;
    }
    /**
     * <code>string srcFile = 1;</code>
     * @param value The bytes for srcFile to set.
     * @return This builder for chaining.
     */
    public Builder setSrcFileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      srcFile_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dstFile_ = "";
    /**
     * <code>string dstFile = 2;</code>
     * @return The dstFile.
     */
    public java.lang.String getDstFile() {
      java.lang.Object ref = dstFile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dstFile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dstFile = 2;</code>
     * @return The bytes for dstFile.
     */
    public com.google.protobuf.ByteString
        getDstFileBytes() {
      java.lang.Object ref = dstFile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dstFile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dstFile = 2;</code>
     * @param value The dstFile to set.
     * @return This builder for chaining.
     */
    public Builder setDstFile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dstFile_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dstFile = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDstFile() {
      
      dstFile_ = getDefaultInstance().getDstFile();
      onChanged();
      return this;
    }
    /**
     * <code>string dstFile = 2;</code>
     * @param value The bytes for dstFile to set.
     * @return This builder for chaining.
     */
    public Builder setDstFileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dstFile_ = value;
      onChanged();
      return this;
    }

    private long srcStart_ ;
    /**
     * <code>int64 srcStart = 3;</code>
     * @return The srcStart.
     */
    public long getSrcStart() {
      return srcStart_;
    }
    /**
     * <code>int64 srcStart = 3;</code>
     * @param value The srcStart to set.
     * @return This builder for chaining.
     */
    public Builder setSrcStart(long value) {
      
      srcStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 srcStart = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSrcStart() {
      
      srcStart_ = 0L;
      onChanged();
      return this;
    }

    private long dstStart_ ;
    /**
     * <code>int64 dstStart = 4;</code>
     * @return The dstStart.
     */
    public long getDstStart() {
      return dstStart_;
    }
    /**
     * <code>int64 dstStart = 4;</code>
     * @param value The dstStart to set.
     * @return This builder for chaining.
     */
    public Builder setDstStart(long value) {
      
      dstStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 dstStart = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDstStart() {
      
      dstStart_ = 0L;
      onChanged();
      return this;
    }

    private long length_ ;
    /**
     * <code>int64 length = 5;</code>
     * @return The length.
     */
    public long getLength() {
      return length_;
    }
    /**
     * <code>int64 length = 5;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(long value) {
      
      length_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 length = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      
      length_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opendedup.grpc.CopyExtentRequest)
  }

  // @@protoc_insertion_point(class_scope:org.opendedup.grpc.CopyExtentRequest)
  private static final org.opendedup.grpc.CopyExtentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opendedup.grpc.CopyExtentRequest();
  }

  public static org.opendedup.grpc.CopyExtentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CopyExtentRequest>
      PARSER = new com.google.protobuf.AbstractParser<CopyExtentRequest>() {
    @java.lang.Override
    public CopyExtentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CopyExtentRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CopyExtentRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CopyExtentRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opendedup.grpc.CopyExtentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

