// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOService.proto

package org.opendedup.grpc;

public interface DataWriteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opendedup.grpc.DataWriteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fileHandle = 1;</code>
   * @return The fileHandle.
   */
  long getFileHandle();

  /**
   * <code>int64 start = 2;</code>
   * @return The start.
   */
  long getStart();

  /**
   * <code>int32 len = 3;</code>
   * @return The len.
   */
  int getLen();

  /**
   * <code>bytes data = 4;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
