// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VolumeService.proto

package org.opendedup.grpc;

/**
 * Protobuf type {@code org.opendedup.grpc.DSEInfo}
 */
public  final class DSEInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opendedup.grpc.DSEInfo)
    DSEInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DSEInfo.newBuilder() to construct.
  private DSEInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DSEInfo() {
    storageType_ = "";
    listenHost_ = "";
    encryptionKey_ = "";
    encryptionIV_ = "";
    cloudAccessKey_ = "";
    cloudSecretKey_ = "";
    bucketName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DSEInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DSEInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            maxSize_ = input.readInt64();
            break;
          }
          case 16: {

            currentSize_ = input.readInt64();
            break;
          }
          case 24: {

            entries_ = input.readInt64();
            break;
          }
          case 32: {

            compressedSize_ = input.readInt64();
            break;
          }
          case 40: {

            freeBlocks_ = input.readInt64();
            break;
          }
          case 48: {

            pageSize_ = input.readInt64();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            storageType_ = s;
            break;
          }
          case 64: {

            listenPort_ = input.readInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            listenHost_ = s;
            break;
          }
          case 80: {

            readSpeed_ = input.readInt32();
            break;
          }
          case 88: {

            writeSpeed_ = input.readInt32();
            break;
          }
          case 96: {

            cacheSize_ = input.readInt64();
            break;
          }
          case 104: {

            maxCacheSize_ = input.readInt64();
            break;
          }
          case 112: {

            listenEncrypted_ = input.readBool();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            encryptionKey_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            encryptionIV_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            cloudAccessKey_ = s;
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            cloudSecretKey_ = s;
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            bucketName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_DSEInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_DSEInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opendedup.grpc.DSEInfo.class, org.opendedup.grpc.DSEInfo.Builder.class);
  }

  public static final int MAXSIZE_FIELD_NUMBER = 1;
  private long maxSize_;
  /**
   * <code>int64 maxSize = 1;</code>
   * @return The maxSize.
   */
  public long getMaxSize() {
    return maxSize_;
  }

  public static final int CURRENTSIZE_FIELD_NUMBER = 2;
  private long currentSize_;
  /**
   * <code>int64 currentSize = 2;</code>
   * @return The currentSize.
   */
  public long getCurrentSize() {
    return currentSize_;
  }

  public static final int ENTRIES_FIELD_NUMBER = 3;
  private long entries_;
  /**
   * <code>int64 entries = 3;</code>
   * @return The entries.
   */
  public long getEntries() {
    return entries_;
  }

  public static final int COMPRESSEDSIZE_FIELD_NUMBER = 4;
  private long compressedSize_;
  /**
   * <code>int64 compressedSize = 4;</code>
   * @return The compressedSize.
   */
  public long getCompressedSize() {
    return compressedSize_;
  }

  public static final int FREEBLOCKS_FIELD_NUMBER = 5;
  private long freeBlocks_;
  /**
   * <code>int64 freeBlocks = 5;</code>
   * @return The freeBlocks.
   */
  public long getFreeBlocks() {
    return freeBlocks_;
  }

  public static final int PAGESIZE_FIELD_NUMBER = 6;
  private long pageSize_;
  /**
   * <code>int64 pageSize = 6;</code>
   * @return The pageSize.
   */
  public long getPageSize() {
    return pageSize_;
  }

  public static final int STORAGETYPE_FIELD_NUMBER = 7;
  private volatile java.lang.Object storageType_;
  /**
   * <code>string storageType = 7;</code>
   * @return The storageType.
   */
  public java.lang.String getStorageType() {
    java.lang.Object ref = storageType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      storageType_ = s;
      return s;
    }
  }
  /**
   * <code>string storageType = 7;</code>
   * @return The bytes for storageType.
   */
  public com.google.protobuf.ByteString
      getStorageTypeBytes() {
    java.lang.Object ref = storageType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      storageType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LISTENPORT_FIELD_NUMBER = 8;
  private int listenPort_;
  /**
   * <code>int32 listenPort = 8;</code>
   * @return The listenPort.
   */
  public int getListenPort() {
    return listenPort_;
  }

  public static final int LISTENHOST_FIELD_NUMBER = 9;
  private volatile java.lang.Object listenHost_;
  /**
   * <code>string listenHost = 9;</code>
   * @return The listenHost.
   */
  public java.lang.String getListenHost() {
    java.lang.Object ref = listenHost_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      listenHost_ = s;
      return s;
    }
  }
  /**
   * <code>string listenHost = 9;</code>
   * @return The bytes for listenHost.
   */
  public com.google.protobuf.ByteString
      getListenHostBytes() {
    java.lang.Object ref = listenHost_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      listenHost_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int READSPEED_FIELD_NUMBER = 10;
  private int readSpeed_;
  /**
   * <code>int32 readSpeed = 10;</code>
   * @return The readSpeed.
   */
  public int getReadSpeed() {
    return readSpeed_;
  }

  public static final int WRITESPEED_FIELD_NUMBER = 11;
  private int writeSpeed_;
  /**
   * <code>int32 writeSpeed = 11;</code>
   * @return The writeSpeed.
   */
  public int getWriteSpeed() {
    return writeSpeed_;
  }

  public static final int CACHESIZE_FIELD_NUMBER = 12;
  private long cacheSize_;
  /**
   * <code>int64 cacheSize = 12;</code>
   * @return The cacheSize.
   */
  public long getCacheSize() {
    return cacheSize_;
  }

  public static final int MAXCACHESIZE_FIELD_NUMBER = 13;
  private long maxCacheSize_;
  /**
   * <code>int64 maxCacheSize = 13;</code>
   * @return The maxCacheSize.
   */
  public long getMaxCacheSize() {
    return maxCacheSize_;
  }

  public static final int LISTENENCRYPTED_FIELD_NUMBER = 14;
  private boolean listenEncrypted_;
  /**
   * <code>bool listenEncrypted = 14;</code>
   * @return The listenEncrypted.
   */
  public boolean getListenEncrypted() {
    return listenEncrypted_;
  }

  public static final int ENCRYPTIONKEY_FIELD_NUMBER = 15;
  private volatile java.lang.Object encryptionKey_;
  /**
   * <code>string encryptionKey = 15;</code>
   * @return The encryptionKey.
   */
  public java.lang.String getEncryptionKey() {
    java.lang.Object ref = encryptionKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      encryptionKey_ = s;
      return s;
    }
  }
  /**
   * <code>string encryptionKey = 15;</code>
   * @return The bytes for encryptionKey.
   */
  public com.google.protobuf.ByteString
      getEncryptionKeyBytes() {
    java.lang.Object ref = encryptionKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      encryptionKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENCRYPTIONIV_FIELD_NUMBER = 16;
  private volatile java.lang.Object encryptionIV_;
  /**
   * <code>string encryptionIV = 16;</code>
   * @return The encryptionIV.
   */
  public java.lang.String getEncryptionIV() {
    java.lang.Object ref = encryptionIV_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      encryptionIV_ = s;
      return s;
    }
  }
  /**
   * <code>string encryptionIV = 16;</code>
   * @return The bytes for encryptionIV.
   */
  public com.google.protobuf.ByteString
      getEncryptionIVBytes() {
    java.lang.Object ref = encryptionIV_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      encryptionIV_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLOUDACCESSKEY_FIELD_NUMBER = 17;
  private volatile java.lang.Object cloudAccessKey_;
  /**
   * <code>string cloudAccessKey = 17;</code>
   * @return The cloudAccessKey.
   */
  public java.lang.String getCloudAccessKey() {
    java.lang.Object ref = cloudAccessKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cloudAccessKey_ = s;
      return s;
    }
  }
  /**
   * <code>string cloudAccessKey = 17;</code>
   * @return The bytes for cloudAccessKey.
   */
  public com.google.protobuf.ByteString
      getCloudAccessKeyBytes() {
    java.lang.Object ref = cloudAccessKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cloudAccessKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLOUDSECRETKEY_FIELD_NUMBER = 18;
  private volatile java.lang.Object cloudSecretKey_;
  /**
   * <code>string cloudSecretKey = 18;</code>
   * @return The cloudSecretKey.
   */
  public java.lang.String getCloudSecretKey() {
    java.lang.Object ref = cloudSecretKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cloudSecretKey_ = s;
      return s;
    }
  }
  /**
   * <code>string cloudSecretKey = 18;</code>
   * @return The bytes for cloudSecretKey.
   */
  public com.google.protobuf.ByteString
      getCloudSecretKeyBytes() {
    java.lang.Object ref = cloudSecretKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cloudSecretKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUCKETNAME_FIELD_NUMBER = 19;
  private volatile java.lang.Object bucketName_;
  /**
   * <code>string bucketName = 19;</code>
   * @return The bucketName.
   */
  public java.lang.String getBucketName() {
    java.lang.Object ref = bucketName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucketName_ = s;
      return s;
    }
  }
  /**
   * <code>string bucketName = 19;</code>
   * @return The bytes for bucketName.
   */
  public com.google.protobuf.ByteString
      getBucketNameBytes() {
    java.lang.Object ref = bucketName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bucketName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (maxSize_ != 0L) {
      output.writeInt64(1, maxSize_);
    }
    if (currentSize_ != 0L) {
      output.writeInt64(2, currentSize_);
    }
    if (entries_ != 0L) {
      output.writeInt64(3, entries_);
    }
    if (compressedSize_ != 0L) {
      output.writeInt64(4, compressedSize_);
    }
    if (freeBlocks_ != 0L) {
      output.writeInt64(5, freeBlocks_);
    }
    if (pageSize_ != 0L) {
      output.writeInt64(6, pageSize_);
    }
    if (!getStorageTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, storageType_);
    }
    if (listenPort_ != 0) {
      output.writeInt32(8, listenPort_);
    }
    if (!getListenHostBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, listenHost_);
    }
    if (readSpeed_ != 0) {
      output.writeInt32(10, readSpeed_);
    }
    if (writeSpeed_ != 0) {
      output.writeInt32(11, writeSpeed_);
    }
    if (cacheSize_ != 0L) {
      output.writeInt64(12, cacheSize_);
    }
    if (maxCacheSize_ != 0L) {
      output.writeInt64(13, maxCacheSize_);
    }
    if (listenEncrypted_ != false) {
      output.writeBool(14, listenEncrypted_);
    }
    if (!getEncryptionKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, encryptionKey_);
    }
    if (!getEncryptionIVBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, encryptionIV_);
    }
    if (!getCloudAccessKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, cloudAccessKey_);
    }
    if (!getCloudSecretKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, cloudSecretKey_);
    }
    if (!getBucketNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, bucketName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (maxSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, maxSize_);
    }
    if (currentSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, currentSize_);
    }
    if (entries_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, entries_);
    }
    if (compressedSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, compressedSize_);
    }
    if (freeBlocks_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, freeBlocks_);
    }
    if (pageSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, pageSize_);
    }
    if (!getStorageTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, storageType_);
    }
    if (listenPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, listenPort_);
    }
    if (!getListenHostBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, listenHost_);
    }
    if (readSpeed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, readSpeed_);
    }
    if (writeSpeed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, writeSpeed_);
    }
    if (cacheSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(12, cacheSize_);
    }
    if (maxCacheSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(13, maxCacheSize_);
    }
    if (listenEncrypted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, listenEncrypted_);
    }
    if (!getEncryptionKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, encryptionKey_);
    }
    if (!getEncryptionIVBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, encryptionIV_);
    }
    if (!getCloudAccessKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, cloudAccessKey_);
    }
    if (!getCloudSecretKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, cloudSecretKey_);
    }
    if (!getBucketNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, bucketName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opendedup.grpc.DSEInfo)) {
      return super.equals(obj);
    }
    org.opendedup.grpc.DSEInfo other = (org.opendedup.grpc.DSEInfo) obj;

    if (getMaxSize()
        != other.getMaxSize()) return false;
    if (getCurrentSize()
        != other.getCurrentSize()) return false;
    if (getEntries()
        != other.getEntries()) return false;
    if (getCompressedSize()
        != other.getCompressedSize()) return false;
    if (getFreeBlocks()
        != other.getFreeBlocks()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (!getStorageType()
        .equals(other.getStorageType())) return false;
    if (getListenPort()
        != other.getListenPort()) return false;
    if (!getListenHost()
        .equals(other.getListenHost())) return false;
    if (getReadSpeed()
        != other.getReadSpeed()) return false;
    if (getWriteSpeed()
        != other.getWriteSpeed()) return false;
    if (getCacheSize()
        != other.getCacheSize()) return false;
    if (getMaxCacheSize()
        != other.getMaxCacheSize()) return false;
    if (getListenEncrypted()
        != other.getListenEncrypted()) return false;
    if (!getEncryptionKey()
        .equals(other.getEncryptionKey())) return false;
    if (!getEncryptionIV()
        .equals(other.getEncryptionIV())) return false;
    if (!getCloudAccessKey()
        .equals(other.getCloudAccessKey())) return false;
    if (!getCloudSecretKey()
        .equals(other.getCloudSecretKey())) return false;
    if (!getBucketName()
        .equals(other.getBucketName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MAXSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxSize());
    hash = (37 * hash) + CURRENTSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentSize());
    hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEntries());
    hash = (37 * hash) + COMPRESSEDSIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCompressedSize());
    hash = (37 * hash) + FREEBLOCKS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFreeBlocks());
    hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPageSize());
    hash = (37 * hash) + STORAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getStorageType().hashCode();
    hash = (37 * hash) + LISTENPORT_FIELD_NUMBER;
    hash = (53 * hash) + getListenPort();
    hash = (37 * hash) + LISTENHOST_FIELD_NUMBER;
    hash = (53 * hash) + getListenHost().hashCode();
    hash = (37 * hash) + READSPEED_FIELD_NUMBER;
    hash = (53 * hash) + getReadSpeed();
    hash = (37 * hash) + WRITESPEED_FIELD_NUMBER;
    hash = (53 * hash) + getWriteSpeed();
    hash = (37 * hash) + CACHESIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCacheSize());
    hash = (37 * hash) + MAXCACHESIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxCacheSize());
    hash = (37 * hash) + LISTENENCRYPTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getListenEncrypted());
    hash = (37 * hash) + ENCRYPTIONKEY_FIELD_NUMBER;
    hash = (53 * hash) + getEncryptionKey().hashCode();
    hash = (37 * hash) + ENCRYPTIONIV_FIELD_NUMBER;
    hash = (53 * hash) + getEncryptionIV().hashCode();
    hash = (37 * hash) + CLOUDACCESSKEY_FIELD_NUMBER;
    hash = (53 * hash) + getCloudAccessKey().hashCode();
    hash = (37 * hash) + CLOUDSECRETKEY_FIELD_NUMBER;
    hash = (53 * hash) + getCloudSecretKey().hashCode();
    hash = (37 * hash) + BUCKETNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBucketName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opendedup.grpc.DSEInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.DSEInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.DSEInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.DSEInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.DSEInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.DSEInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.DSEInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.DSEInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opendedup.grpc.DSEInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.DSEInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opendedup.grpc.DSEInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.DSEInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opendedup.grpc.DSEInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opendedup.grpc.DSEInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opendedup.grpc.DSEInfo)
      org.opendedup.grpc.DSEInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_DSEInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_DSEInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opendedup.grpc.DSEInfo.class, org.opendedup.grpc.DSEInfo.Builder.class);
    }

    // Construct using org.opendedup.grpc.DSEInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      maxSize_ = 0L;

      currentSize_ = 0L;

      entries_ = 0L;

      compressedSize_ = 0L;

      freeBlocks_ = 0L;

      pageSize_ = 0L;

      storageType_ = "";

      listenPort_ = 0;

      listenHost_ = "";

      readSpeed_ = 0;

      writeSpeed_ = 0;

      cacheSize_ = 0L;

      maxCacheSize_ = 0L;

      listenEncrypted_ = false;

      encryptionKey_ = "";

      encryptionIV_ = "";

      cloudAccessKey_ = "";

      cloudSecretKey_ = "";

      bucketName_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_DSEInfo_descriptor;
    }

    @java.lang.Override
    public org.opendedup.grpc.DSEInfo getDefaultInstanceForType() {
      return org.opendedup.grpc.DSEInfo.getDefaultInstance();
    }

    @java.lang.Override
    public org.opendedup.grpc.DSEInfo build() {
      org.opendedup.grpc.DSEInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opendedup.grpc.DSEInfo buildPartial() {
      org.opendedup.grpc.DSEInfo result = new org.opendedup.grpc.DSEInfo(this);
      result.maxSize_ = maxSize_;
      result.currentSize_ = currentSize_;
      result.entries_ = entries_;
      result.compressedSize_ = compressedSize_;
      result.freeBlocks_ = freeBlocks_;
      result.pageSize_ = pageSize_;
      result.storageType_ = storageType_;
      result.listenPort_ = listenPort_;
      result.listenHost_ = listenHost_;
      result.readSpeed_ = readSpeed_;
      result.writeSpeed_ = writeSpeed_;
      result.cacheSize_ = cacheSize_;
      result.maxCacheSize_ = maxCacheSize_;
      result.listenEncrypted_ = listenEncrypted_;
      result.encryptionKey_ = encryptionKey_;
      result.encryptionIV_ = encryptionIV_;
      result.cloudAccessKey_ = cloudAccessKey_;
      result.cloudSecretKey_ = cloudSecretKey_;
      result.bucketName_ = bucketName_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opendedup.grpc.DSEInfo) {
        return mergeFrom((org.opendedup.grpc.DSEInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opendedup.grpc.DSEInfo other) {
      if (other == org.opendedup.grpc.DSEInfo.getDefaultInstance()) return this;
      if (other.getMaxSize() != 0L) {
        setMaxSize(other.getMaxSize());
      }
      if (other.getCurrentSize() != 0L) {
        setCurrentSize(other.getCurrentSize());
      }
      if (other.getEntries() != 0L) {
        setEntries(other.getEntries());
      }
      if (other.getCompressedSize() != 0L) {
        setCompressedSize(other.getCompressedSize());
      }
      if (other.getFreeBlocks() != 0L) {
        setFreeBlocks(other.getFreeBlocks());
      }
      if (other.getPageSize() != 0L) {
        setPageSize(other.getPageSize());
      }
      if (!other.getStorageType().isEmpty()) {
        storageType_ = other.storageType_;
        onChanged();
      }
      if (other.getListenPort() != 0) {
        setListenPort(other.getListenPort());
      }
      if (!other.getListenHost().isEmpty()) {
        listenHost_ = other.listenHost_;
        onChanged();
      }
      if (other.getReadSpeed() != 0) {
        setReadSpeed(other.getReadSpeed());
      }
      if (other.getWriteSpeed() != 0) {
        setWriteSpeed(other.getWriteSpeed());
      }
      if (other.getCacheSize() != 0L) {
        setCacheSize(other.getCacheSize());
      }
      if (other.getMaxCacheSize() != 0L) {
        setMaxCacheSize(other.getMaxCacheSize());
      }
      if (other.getListenEncrypted() != false) {
        setListenEncrypted(other.getListenEncrypted());
      }
      if (!other.getEncryptionKey().isEmpty()) {
        encryptionKey_ = other.encryptionKey_;
        onChanged();
      }
      if (!other.getEncryptionIV().isEmpty()) {
        encryptionIV_ = other.encryptionIV_;
        onChanged();
      }
      if (!other.getCloudAccessKey().isEmpty()) {
        cloudAccessKey_ = other.cloudAccessKey_;
        onChanged();
      }
      if (!other.getCloudSecretKey().isEmpty()) {
        cloudSecretKey_ = other.cloudSecretKey_;
        onChanged();
      }
      if (!other.getBucketName().isEmpty()) {
        bucketName_ = other.bucketName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.opendedup.grpc.DSEInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.opendedup.grpc.DSEInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long maxSize_ ;
    /**
     * <code>int64 maxSize = 1;</code>
     * @return The maxSize.
     */
    public long getMaxSize() {
      return maxSize_;
    }
    /**
     * <code>int64 maxSize = 1;</code>
     * @param value The maxSize to set.
     * @return This builder for chaining.
     */
    public Builder setMaxSize(long value) {
      
      maxSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 maxSize = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxSize() {
      
      maxSize_ = 0L;
      onChanged();
      return this;
    }

    private long currentSize_ ;
    /**
     * <code>int64 currentSize = 2;</code>
     * @return The currentSize.
     */
    public long getCurrentSize() {
      return currentSize_;
    }
    /**
     * <code>int64 currentSize = 2;</code>
     * @param value The currentSize to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentSize(long value) {
      
      currentSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 currentSize = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentSize() {
      
      currentSize_ = 0L;
      onChanged();
      return this;
    }

    private long entries_ ;
    /**
     * <code>int64 entries = 3;</code>
     * @return The entries.
     */
    public long getEntries() {
      return entries_;
    }
    /**
     * <code>int64 entries = 3;</code>
     * @param value The entries to set.
     * @return This builder for chaining.
     */
    public Builder setEntries(long value) {
      
      entries_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 entries = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEntries() {
      
      entries_ = 0L;
      onChanged();
      return this;
    }

    private long compressedSize_ ;
    /**
     * <code>int64 compressedSize = 4;</code>
     * @return The compressedSize.
     */
    public long getCompressedSize() {
      return compressedSize_;
    }
    /**
     * <code>int64 compressedSize = 4;</code>
     * @param value The compressedSize to set.
     * @return This builder for chaining.
     */
    public Builder setCompressedSize(long value) {
      
      compressedSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 compressedSize = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompressedSize() {
      
      compressedSize_ = 0L;
      onChanged();
      return this;
    }

    private long freeBlocks_ ;
    /**
     * <code>int64 freeBlocks = 5;</code>
     * @return The freeBlocks.
     */
    public long getFreeBlocks() {
      return freeBlocks_;
    }
    /**
     * <code>int64 freeBlocks = 5;</code>
     * @param value The freeBlocks to set.
     * @return This builder for chaining.
     */
    public Builder setFreeBlocks(long value) {
      
      freeBlocks_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 freeBlocks = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearFreeBlocks() {
      
      freeBlocks_ = 0L;
      onChanged();
      return this;
    }

    private long pageSize_ ;
    /**
     * <code>int64 pageSize = 6;</code>
     * @return The pageSize.
     */
    public long getPageSize() {
      return pageSize_;
    }
    /**
     * <code>int64 pageSize = 6;</code>
     * @param value The pageSize to set.
     * @return This builder for chaining.
     */
    public Builder setPageSize(long value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 pageSize = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object storageType_ = "";
    /**
     * <code>string storageType = 7;</code>
     * @return The storageType.
     */
    public java.lang.String getStorageType() {
      java.lang.Object ref = storageType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        storageType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string storageType = 7;</code>
     * @return The bytes for storageType.
     */
    public com.google.protobuf.ByteString
        getStorageTypeBytes() {
      java.lang.Object ref = storageType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        storageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string storageType = 7;</code>
     * @param value The storageType to set.
     * @return This builder for chaining.
     */
    public Builder setStorageType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      storageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string storageType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStorageType() {
      
      storageType_ = getDefaultInstance().getStorageType();
      onChanged();
      return this;
    }
    /**
     * <code>string storageType = 7;</code>
     * @param value The bytes for storageType to set.
     * @return This builder for chaining.
     */
    public Builder setStorageTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      storageType_ = value;
      onChanged();
      return this;
    }

    private int listenPort_ ;
    /**
     * <code>int32 listenPort = 8;</code>
     * @return The listenPort.
     */
    public int getListenPort() {
      return listenPort_;
    }
    /**
     * <code>int32 listenPort = 8;</code>
     * @param value The listenPort to set.
     * @return This builder for chaining.
     */
    public Builder setListenPort(int value) {
      
      listenPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 listenPort = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearListenPort() {
      
      listenPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object listenHost_ = "";
    /**
     * <code>string listenHost = 9;</code>
     * @return The listenHost.
     */
    public java.lang.String getListenHost() {
      java.lang.Object ref = listenHost_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        listenHost_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string listenHost = 9;</code>
     * @return The bytes for listenHost.
     */
    public com.google.protobuf.ByteString
        getListenHostBytes() {
      java.lang.Object ref = listenHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        listenHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string listenHost = 9;</code>
     * @param value The listenHost to set.
     * @return This builder for chaining.
     */
    public Builder setListenHost(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      listenHost_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string listenHost = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearListenHost() {
      
      listenHost_ = getDefaultInstance().getListenHost();
      onChanged();
      return this;
    }
    /**
     * <code>string listenHost = 9;</code>
     * @param value The bytes for listenHost to set.
     * @return This builder for chaining.
     */
    public Builder setListenHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      listenHost_ = value;
      onChanged();
      return this;
    }

    private int readSpeed_ ;
    /**
     * <code>int32 readSpeed = 10;</code>
     * @return The readSpeed.
     */
    public int getReadSpeed() {
      return readSpeed_;
    }
    /**
     * <code>int32 readSpeed = 10;</code>
     * @param value The readSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setReadSpeed(int value) {
      
      readSpeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 readSpeed = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadSpeed() {
      
      readSpeed_ = 0;
      onChanged();
      return this;
    }

    private int writeSpeed_ ;
    /**
     * <code>int32 writeSpeed = 11;</code>
     * @return The writeSpeed.
     */
    public int getWriteSpeed() {
      return writeSpeed_;
    }
    /**
     * <code>int32 writeSpeed = 11;</code>
     * @param value The writeSpeed to set.
     * @return This builder for chaining.
     */
    public Builder setWriteSpeed(int value) {
      
      writeSpeed_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 writeSpeed = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearWriteSpeed() {
      
      writeSpeed_ = 0;
      onChanged();
      return this;
    }

    private long cacheSize_ ;
    /**
     * <code>int64 cacheSize = 12;</code>
     * @return The cacheSize.
     */
    public long getCacheSize() {
      return cacheSize_;
    }
    /**
     * <code>int64 cacheSize = 12;</code>
     * @param value The cacheSize to set.
     * @return This builder for chaining.
     */
    public Builder setCacheSize(long value) {
      
      cacheSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cacheSize = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearCacheSize() {
      
      cacheSize_ = 0L;
      onChanged();
      return this;
    }

    private long maxCacheSize_ ;
    /**
     * <code>int64 maxCacheSize = 13;</code>
     * @return The maxCacheSize.
     */
    public long getMaxCacheSize() {
      return maxCacheSize_;
    }
    /**
     * <code>int64 maxCacheSize = 13;</code>
     * @param value The maxCacheSize to set.
     * @return This builder for chaining.
     */
    public Builder setMaxCacheSize(long value) {
      
      maxCacheSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 maxCacheSize = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxCacheSize() {
      
      maxCacheSize_ = 0L;
      onChanged();
      return this;
    }

    private boolean listenEncrypted_ ;
    /**
     * <code>bool listenEncrypted = 14;</code>
     * @return The listenEncrypted.
     */
    public boolean getListenEncrypted() {
      return listenEncrypted_;
    }
    /**
     * <code>bool listenEncrypted = 14;</code>
     * @param value The listenEncrypted to set.
     * @return This builder for chaining.
     */
    public Builder setListenEncrypted(boolean value) {
      
      listenEncrypted_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool listenEncrypted = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearListenEncrypted() {
      
      listenEncrypted_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object encryptionKey_ = "";
    /**
     * <code>string encryptionKey = 15;</code>
     * @return The encryptionKey.
     */
    public java.lang.String getEncryptionKey() {
      java.lang.Object ref = encryptionKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encryptionKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string encryptionKey = 15;</code>
     * @return The bytes for encryptionKey.
     */
    public com.google.protobuf.ByteString
        getEncryptionKeyBytes() {
      java.lang.Object ref = encryptionKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encryptionKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string encryptionKey = 15;</code>
     * @param value The encryptionKey to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptionKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encryptionKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string encryptionKey = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptionKey() {
      
      encryptionKey_ = getDefaultInstance().getEncryptionKey();
      onChanged();
      return this;
    }
    /**
     * <code>string encryptionKey = 15;</code>
     * @param value The bytes for encryptionKey to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptionKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      encryptionKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object encryptionIV_ = "";
    /**
     * <code>string encryptionIV = 16;</code>
     * @return The encryptionIV.
     */
    public java.lang.String getEncryptionIV() {
      java.lang.Object ref = encryptionIV_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        encryptionIV_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string encryptionIV = 16;</code>
     * @return The bytes for encryptionIV.
     */
    public com.google.protobuf.ByteString
        getEncryptionIVBytes() {
      java.lang.Object ref = encryptionIV_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        encryptionIV_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string encryptionIV = 16;</code>
     * @param value The encryptionIV to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptionIV(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      encryptionIV_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string encryptionIV = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptionIV() {
      
      encryptionIV_ = getDefaultInstance().getEncryptionIV();
      onChanged();
      return this;
    }
    /**
     * <code>string encryptionIV = 16;</code>
     * @param value The bytes for encryptionIV to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptionIVBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      encryptionIV_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cloudAccessKey_ = "";
    /**
     * <code>string cloudAccessKey = 17;</code>
     * @return The cloudAccessKey.
     */
    public java.lang.String getCloudAccessKey() {
      java.lang.Object ref = cloudAccessKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cloudAccessKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cloudAccessKey = 17;</code>
     * @return The bytes for cloudAccessKey.
     */
    public com.google.protobuf.ByteString
        getCloudAccessKeyBytes() {
      java.lang.Object ref = cloudAccessKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cloudAccessKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cloudAccessKey = 17;</code>
     * @param value The cloudAccessKey to set.
     * @return This builder for chaining.
     */
    public Builder setCloudAccessKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cloudAccessKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cloudAccessKey = 17;</code>
     * @return This builder for chaining.
     */
    public Builder clearCloudAccessKey() {
      
      cloudAccessKey_ = getDefaultInstance().getCloudAccessKey();
      onChanged();
      return this;
    }
    /**
     * <code>string cloudAccessKey = 17;</code>
     * @param value The bytes for cloudAccessKey to set.
     * @return This builder for chaining.
     */
    public Builder setCloudAccessKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cloudAccessKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cloudSecretKey_ = "";
    /**
     * <code>string cloudSecretKey = 18;</code>
     * @return The cloudSecretKey.
     */
    public java.lang.String getCloudSecretKey() {
      java.lang.Object ref = cloudSecretKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cloudSecretKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cloudSecretKey = 18;</code>
     * @return The bytes for cloudSecretKey.
     */
    public com.google.protobuf.ByteString
        getCloudSecretKeyBytes() {
      java.lang.Object ref = cloudSecretKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cloudSecretKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cloudSecretKey = 18;</code>
     * @param value The cloudSecretKey to set.
     * @return This builder for chaining.
     */
    public Builder setCloudSecretKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cloudSecretKey_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cloudSecretKey = 18;</code>
     * @return This builder for chaining.
     */
    public Builder clearCloudSecretKey() {
      
      cloudSecretKey_ = getDefaultInstance().getCloudSecretKey();
      onChanged();
      return this;
    }
    /**
     * <code>string cloudSecretKey = 18;</code>
     * @param value The bytes for cloudSecretKey to set.
     * @return This builder for chaining.
     */
    public Builder setCloudSecretKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cloudSecretKey_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object bucketName_ = "";
    /**
     * <code>string bucketName = 19;</code>
     * @return The bucketName.
     */
    public java.lang.String getBucketName() {
      java.lang.Object ref = bucketName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucketName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bucketName = 19;</code>
     * @return The bytes for bucketName.
     */
    public com.google.protobuf.ByteString
        getBucketNameBytes() {
      java.lang.Object ref = bucketName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bucketName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bucketName = 19;</code>
     * @param value The bucketName to set.
     * @return This builder for chaining.
     */
    public Builder setBucketName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bucketName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string bucketName = 19;</code>
     * @return This builder for chaining.
     */
    public Builder clearBucketName() {
      
      bucketName_ = getDefaultInstance().getBucketName();
      onChanged();
      return this;
    }
    /**
     * <code>string bucketName = 19;</code>
     * @param value The bytes for bucketName to set.
     * @return This builder for chaining.
     */
    public Builder setBucketNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      bucketName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opendedup.grpc.DSEInfo)
  }

  // @@protoc_insertion_point(class_scope:org.opendedup.grpc.DSEInfo)
  private static final org.opendedup.grpc.DSEInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opendedup.grpc.DSEInfo();
  }

  public static org.opendedup.grpc.DSEInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DSEInfo>
      PARSER = new com.google.protobuf.AbstractParser<DSEInfo>() {
    @java.lang.Override
    public DSEInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DSEInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DSEInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DSEInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opendedup.grpc.DSEInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

