// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOService.proto

package org.opendedup.grpc;

public interface FileSnapshotRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opendedup.grpc.FileSnapshotRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string src = 1;</code>
   * @return The src.
   */
  java.lang.String getSrc();
  /**
   * <code>string src = 1;</code>
   * @return The bytes for src.
   */
  com.google.protobuf.ByteString
      getSrcBytes();

  /**
   * <code>string dest = 2;</code>
   * @return The dest.
   */
  java.lang.String getDest();
  /**
   * <code>string dest = 2;</code>
   * @return The bytes for dest.
   */
  com.google.protobuf.ByteString
      getDestBytes();
}
