// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOService.proto

package org.opendedup.grpc;

public interface FileCloseRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opendedup.grpc.FileCloseRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fileHandle = 1;</code>
   * @return The fileHandle.
   */
  long getFileHandle();
}
