// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOService.proto

package org.opendedup.grpc;

public final class IOService {
  private IOService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_DataWriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_DataWriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_DataWriteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_DataWriteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_MkDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_MkDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_MkDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_MkDirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_RmDirRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_RmDirRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_RmDirResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_RmDirResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_UnlinkRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_UnlinkRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_UnlinkResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_UnlinkResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_DataReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_DataReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_DataReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_DataReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileCloseRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileCloseRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileCloseResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileCloseResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_MkNodRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_MkNodRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_MkNodResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_MkNodResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileOpenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileOpenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileExistsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileExistsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileExistsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileExistsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileOpenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileOpenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileSnapshotRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileSnapshotRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileSnapshotResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileSnapshotResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileRenameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileRenameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_FileRenameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_FileRenameResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_CopyExtentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_CopyExtentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_CopyExtentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_CopyExtentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_SetUserMetaDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_SetUserMetaDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_SetUserMetaDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_SetUserMetaDataResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_GetCloudFileRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_GetCloudFileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_opendedup_grpc_GetCloudFileResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_opendedup_grpc_GetCloudFileResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017IOService.proto\022\022org.opendedup.grpc\032\016F" +
      "ileInfo.proto\"P\n\020DataWriteRequest\022\022\n\nfil" +
      "eHandle\030\001 \001(\003\022\r\n\005start\030\002 \001(\003\022\013\n\003len\030\003 \001(" +
      "\005\022\014\n\004data\030\004 \001(\014\"U\n\021DataWriteResponse\022\r\n\005" +
      "error\030\001 \001(\t\0221\n\terrorCode\030\002 \001(\0162\036.org.ope" +
      "ndedup.grpc.errorCodes\"\034\n\014MkDirRequest\022\014" +
      "\n\004path\030\001 \001(\t\"Q\n\rMkDirResponse\022\r\n\005error\030\001" +
      " \001(\t\0221\n\terrorCode\030\002 \001(\0162\036.org.opendedup." +
      "grpc.errorCodes\"\034\n\014RmDirRequest\022\014\n\004path\030" +
      "\001 \001(\t\"Q\n\rRmDirResponse\022\r\n\005error\030\001 \001(\t\0221\n" +
      "\terrorCode\030\002 \001(\0162\036.org.opendedup.grpc.er" +
      "rorCodes\"\035\n\rUnlinkRequest\022\014\n\004path\030\001 \001(\t\"" +
      "R\n\016UnlinkResponse\022\r\n\005error\030\001 \001(\t\0221\n\terro" +
      "rCode\030\002 \001(\0162\036.org.opendedup.grpc.errorCo" +
      "des\"A\n\017DataReadRequest\022\022\n\nfileHandle\030\001 \001" +
      "(\003\022\r\n\005start\030\002 \001(\003\022\013\n\003len\030\003 \001(\005\"p\n\020DataRe" +
      "adResponse\022\014\n\004data\030\001 \001(\014\022\014\n\004read\030\002 \001(\005\022\r" +
      "\n\005error\030\003 \001(\t\0221\n\terrorCode\030\004 \001(\0162\036.org.o" +
      "pendedup.grpc.errorCodes\"&\n\020FileCloseReq" +
      "uest\022\022\n\nfileHandle\030\001 \001(\003\"U\n\021FileCloseRes" +
      "ponse\022\r\n\005error\030\001 \001(\t\0221\n\terrorCode\030\002 \001(\0162" +
      "\036.org.opendedup.grpc.errorCodes\"\034\n\014MkNod" +
      "Request\022\014\n\004path\030\001 \001(\t\"Q\n\rMkNodResponse\022\r" +
      "\n\005error\030\001 \001(\t\0221\n\terrorCode\030\002 \001(\0162\036.org.o" +
      "pendedup.grpc.errorCodes\"\037\n\017FileOpenRequ" +
      "est\022\014\n\004path\030\001 \001(\t\"!\n\021FileExistsRequest\022\014" +
      "\n\004path\030\001 \001(\t\"f\n\022FileExistsResponse\022\016\n\006ex" +
      "ists\030\001 \001(\010\022\r\n\005error\030\002 \001(\t\0221\n\terrorCode\030\003" +
      " \001(\0162\036.org.opendedup.grpc.errorCodes\"h\n\020" +
      "FileOpenResponse\022\022\n\nfileHandle\030\001 \001(\003\022\r\n\005" +
      "error\030\002 \001(\t\0221\n\terrorCode\030\003 \001(\0162\036.org.ope" +
      "ndedup.grpc.errorCodes\"0\n\023FileSnapshotRe" +
      "quest\022\013\n\003src\030\001 \001(\t\022\014\n\004dest\030\002 \001(\t\"X\n\024File" +
      "SnapshotResponse\022\r\n\005error\030\002 \001(\t\0221\n\terror" +
      "Code\030\003 \001(\0162\036.org.opendedup.grpc.errorCod" +
      "es\".\n\021FileRenameRequest\022\013\n\003src\030\001 \001(\t\022\014\n\004" +
      "dest\030\002 \001(\t\"V\n\022FileRenameResponse\022\r\n\005erro" +
      "r\030\002 \001(\t\0221\n\terrorCode\030\003 \001(\0162\036.org.opended" +
      "up.grpc.errorCodes\"i\n\021CopyExtentRequest\022" +
      "\017\n\007srcFile\030\001 \001(\t\022\017\n\007dstFile\030\002 \001(\t\022\020\n\010src" +
      "Start\030\003 \001(\003\022\020\n\010dstStart\030\004 \001(\003\022\016\n\006length\030" +
      "\005 \001(\003\"g\n\022CopyExtentResponse\022\r\n\005error\030\001 \001" +
      "(\t\0221\n\terrorCode\030\002 \001(\0162\036.org.opendedup.gr" +
      "pc.errorCodes\022\017\n\007written\030\003 \001(\003\"b\n\026SetUse" +
      "rMetaDataRequest\022:\n\016fileAttributes\030\001 \003(\013" +
      "2\".org.opendedup.grpc.FileAttributes\022\014\n\004" +
      "Path\030\002 \001(\t\"[\n\027SetUserMetaDataResponse\022\r\n" +
      "\005error\030\001 \001(\t\0221\n\terrorCode\030\002 \001(\0162\036.org.op" +
      "endedup.grpc.errorCodes\"Y\n\023GetCloudFileR" +
      "equest\022\014\n\004file\030\001 \001(\t\022\017\n\007dstfile\030\002 \001(\t\022\021\n" +
      "\toverwrite\030\003 \001(\010\022\020\n\010changeid\030\004 \001(\t\"i\n\024Ge" +
      "tCloudFileResponse\022\017\n\007eventID\030\001 \001(\t\022\r\n\005e" +
      "rror\030\002 \001(\t\0221\n\terrorCode\030\003 \001(\0162\036.org.open" +
      "dedup.grpc.errorCodes2\314\014\n\rFileIOService\022" +
      "L\n\005MkDir\022 .org.opendedup.grpc.MkDirReque" +
      "st\032!.org.opendedup.grpc.MkDirResponse\022L\n" +
      "\005RmDir\022 .org.opendedup.grpc.RmDirRequest" +
      "\032!.org.opendedup.grpc.RmDirResponse\022O\n\006U" +
      "nlink\022!.org.opendedup.grpc.UnlinkRequest" +
      "\032\".org.opendedup.grpc.UnlinkResponse\022T\n\005" +
      "Write\022$.org.opendedup.grpc.DataWriteRequ" +
      "est\032%.org.opendedup.grpc.DataWriteRespon" +
      "se\022Q\n\004Read\022#.org.opendedup.grpc.DataRead" +
      "Request\032$.org.opendedup.grpc.DataReadRes" +
      "ponse\022V\n\007Release\022$.org.opendedup.grpc.Fi" +
      "leCloseRequest\032%.org.opendedup.grpc.File" +
      "CloseResponse\022L\n\005Mknod\022 .org.opendedup.g" +
      "rpc.MkNodRequest\032!.org.opendedup.grpc.Mk" +
      "NodResponse\022Q\n\004Open\022#.org.opendedup.grpc" +
      ".FileOpenRequest\032$.org.opendedup.grpc.Fi" +
      "leOpenResponse\022[\n\013GetFileInfo\022#.org.open" +
      "dedup.grpc.FileInfoRequest\032\'.org.opended" +
      "up.grpc.FileMessageResponse\022_\n\nCreateCop" +
      "y\022\'.org.opendedup.grpc.FileSnapshotReque" +
      "st\032(.org.opendedup.grpc.FileSnapshotResp" +
      "onse\022[\n\nFileExists\022%.org.opendedup.grpc." +
      "FileExistsRequest\032&.org.opendedup.grpc.F" +
      "ileExistsResponse\022O\n\010MkDirAll\022 .org.open" +
      "dedup.grpc.MkDirRequest\032!.org.opendedup." +
      "grpc.MkDirResponse\022T\n\004Stat\022#.org.opended" +
      "up.grpc.FileInfoRequest\032\'.org.opendedup." +
      "grpc.FileMessageResponse\022W\n\006Rename\022%.org" +
      ".opendedup.grpc.FileRenameRequest\032&.org." +
      "opendedup.grpc.FileRenameResponse\022[\n\nCop" +
      "yExtent\022%.org.opendedup.grpc.CopyExtentR" +
      "equest\032&.org.opendedup.grpc.CopyExtentRe" +
      "sponse\022j\n\017SetUserMetaData\022*.org.opendedu" +
      "p.grpc.SetUserMetaDataRequest\032+.org.open" +
      "dedup.grpc.SetUserMetaDataResponse\022a\n\014Ge" +
      "tCloudFile\022\'.org.opendedup.grpc.GetCloud" +
      "FileRequest\032(.org.opendedup.grpc.GetClou" +
      "dFileResponse\022e\n\020GetCloudMetaFile\022\'.org." +
      "opendedup.grpc.GetCloudFileRequest\032(.org" +
      ".opendedup.grpc.GetCloudFileResponseB2P\001" +
      "Z.github.com/opendedup/sdfs-client-go/sd" +
      "fs/;sdfsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.opendedup.grpc.FileInfo.getDescriptor(),
        });
    internal_static_org_opendedup_grpc_DataWriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_opendedup_grpc_DataWriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_DataWriteRequest_descriptor,
        new java.lang.String[] { "FileHandle", "Start", "Len", "Data", });
    internal_static_org_opendedup_grpc_DataWriteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_opendedup_grpc_DataWriteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_DataWriteResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_MkDirRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_opendedup_grpc_MkDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_MkDirRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_org_opendedup_grpc_MkDirResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_org_opendedup_grpc_MkDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_MkDirResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_RmDirRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_org_opendedup_grpc_RmDirRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_RmDirRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_org_opendedup_grpc_RmDirResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_org_opendedup_grpc_RmDirResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_RmDirResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_UnlinkRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_org_opendedup_grpc_UnlinkRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_UnlinkRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_org_opendedup_grpc_UnlinkResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_org_opendedup_grpc_UnlinkResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_UnlinkResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_DataReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_org_opendedup_grpc_DataReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_DataReadRequest_descriptor,
        new java.lang.String[] { "FileHandle", "Start", "Len", });
    internal_static_org_opendedup_grpc_DataReadResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_org_opendedup_grpc_DataReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_DataReadResponse_descriptor,
        new java.lang.String[] { "Data", "Read", "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_FileCloseRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_org_opendedup_grpc_FileCloseRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileCloseRequest_descriptor,
        new java.lang.String[] { "FileHandle", });
    internal_static_org_opendedup_grpc_FileCloseResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_org_opendedup_grpc_FileCloseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileCloseResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_MkNodRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_org_opendedup_grpc_MkNodRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_MkNodRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_org_opendedup_grpc_MkNodResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_org_opendedup_grpc_MkNodResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_MkNodResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_FileOpenRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_org_opendedup_grpc_FileOpenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileOpenRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_org_opendedup_grpc_FileExistsRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_org_opendedup_grpc_FileExistsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileExistsRequest_descriptor,
        new java.lang.String[] { "Path", });
    internal_static_org_opendedup_grpc_FileExistsResponse_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_org_opendedup_grpc_FileExistsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileExistsResponse_descriptor,
        new java.lang.String[] { "Exists", "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_FileOpenResponse_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_org_opendedup_grpc_FileOpenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileOpenResponse_descriptor,
        new java.lang.String[] { "FileHandle", "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_FileSnapshotRequest_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_org_opendedup_grpc_FileSnapshotRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileSnapshotRequest_descriptor,
        new java.lang.String[] { "Src", "Dest", });
    internal_static_org_opendedup_grpc_FileSnapshotResponse_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_org_opendedup_grpc_FileSnapshotResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileSnapshotResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_FileRenameRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_org_opendedup_grpc_FileRenameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileRenameRequest_descriptor,
        new java.lang.String[] { "Src", "Dest", });
    internal_static_org_opendedup_grpc_FileRenameResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_org_opendedup_grpc_FileRenameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_FileRenameResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_CopyExtentRequest_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_org_opendedup_grpc_CopyExtentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_CopyExtentRequest_descriptor,
        new java.lang.String[] { "SrcFile", "DstFile", "SrcStart", "DstStart", "Length", });
    internal_static_org_opendedup_grpc_CopyExtentResponse_descriptor =
      getDescriptor().getMessageTypes().get(23);
    internal_static_org_opendedup_grpc_CopyExtentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_CopyExtentResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", "Written", });
    internal_static_org_opendedup_grpc_SetUserMetaDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(24);
    internal_static_org_opendedup_grpc_SetUserMetaDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_SetUserMetaDataRequest_descriptor,
        new java.lang.String[] { "FileAttributes", "Path", });
    internal_static_org_opendedup_grpc_SetUserMetaDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(25);
    internal_static_org_opendedup_grpc_SetUserMetaDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_SetUserMetaDataResponse_descriptor,
        new java.lang.String[] { "Error", "ErrorCode", });
    internal_static_org_opendedup_grpc_GetCloudFileRequest_descriptor =
      getDescriptor().getMessageTypes().get(26);
    internal_static_org_opendedup_grpc_GetCloudFileRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_GetCloudFileRequest_descriptor,
        new java.lang.String[] { "File", "Dstfile", "Overwrite", "Changeid", });
    internal_static_org_opendedup_grpc_GetCloudFileResponse_descriptor =
      getDescriptor().getMessageTypes().get(27);
    internal_static_org_opendedup_grpc_GetCloudFileResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_opendedup_grpc_GetCloudFileResponse_descriptor,
        new java.lang.String[] { "EventID", "Error", "ErrorCode", });
    org.opendedup.grpc.FileInfo.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
