// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VolumeService.proto

package org.opendedup.grpc;

/**
 * Protobuf type {@code org.opendedup.grpc.MessageQueue}
 */
public final class MessageQueue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opendedup.grpc.MessageQueue)
    MessageQueueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageQueue.newBuilder() to construct.
  private MessageQueue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageQueue() {
    hostName_ = "";
    mqType_ = 0;
    topic_ = "";
    authInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageQueue();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageQueue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hostName_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            mqType_ = rawValue;
            break;
          }
          case 24: {

            port_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            authInfo_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_MessageQueue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_MessageQueue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opendedup.grpc.MessageQueue.class, org.opendedup.grpc.MessageQueue.Builder.class);
  }

  /**
   * Protobuf enum {@code org.opendedup.grpc.MessageQueue.MQType}
   */
  public enum MQType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RabbitMQ = 0;</code>
     */
    RabbitMQ(0),
    /**
     * <code>PubSub = 1;</code>
     */
    PubSub(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RabbitMQ = 0;</code>
     */
    public static final int RabbitMQ_VALUE = 0;
    /**
     * <code>PubSub = 1;</code>
     */
    public static final int PubSub_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MQType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MQType forNumber(int value) {
      switch (value) {
        case 0: return RabbitMQ;
        case 1: return PubSub;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MQType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MQType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MQType>() {
            public MQType findValueByNumber(int number) {
              return MQType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.opendedup.grpc.MessageQueue.getDescriptor().getEnumTypes().get(0);
    }

    private static final MQType[] VALUES = values();

    public static MQType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MQType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.opendedup.grpc.MessageQueue.MQType)
  }

  public static final int HOSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object hostName_;
  /**
   * <code>string hostName = 1;</code>
   * @return The hostName.
   */
  @java.lang.Override
  public java.lang.String getHostName() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostName_ = s;
      return s;
    }
  }
  /**
   * <code>string hostName = 1;</code>
   * @return The bytes for hostName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostNameBytes() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MQTYPE_FIELD_NUMBER = 2;
  private int mqType_;
  /**
   * <code>.org.opendedup.grpc.MessageQueue.MQType mqType = 2;</code>
   * @return The enum numeric value on the wire for mqType.
   */
  @java.lang.Override public int getMqTypeValue() {
    return mqType_;
  }
  /**
   * <code>.org.opendedup.grpc.MessageQueue.MQType mqType = 2;</code>
   * @return The mqType.
   */
  @java.lang.Override public org.opendedup.grpc.MessageQueue.MQType getMqType() {
    @SuppressWarnings("deprecation")
    org.opendedup.grpc.MessageQueue.MQType result = org.opendedup.grpc.MessageQueue.MQType.valueOf(mqType_);
    return result == null ? org.opendedup.grpc.MessageQueue.MQType.UNRECOGNIZED : result;
  }

  public static final int PORT_FIELD_NUMBER = 3;
  private int port_;
  /**
   * <code>int32 port = 3;</code>
   * @return The port.
   */
  @java.lang.Override
  public int getPort() {
    return port_;
  }

  public static final int TOPIC_FIELD_NUMBER = 4;
  private volatile java.lang.Object topic_;
  /**
   * <code>string topic = 4;</code>
   * @return The topic.
   */
  @java.lang.Override
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>string topic = 4;</code>
   * @return The bytes for topic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHINFO_FIELD_NUMBER = 5;
  private volatile java.lang.Object authInfo_;
  /**
   * <code>string authInfo = 5;</code>
   * @return The authInfo.
   */
  @java.lang.Override
  public java.lang.String getAuthInfo() {
    java.lang.Object ref = authInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string authInfo = 5;</code>
   * @return The bytes for authInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthInfoBytes() {
    java.lang.Object ref = authInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHostNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostName_);
    }
    if (mqType_ != org.opendedup.grpc.MessageQueue.MQType.RabbitMQ.getNumber()) {
      output.writeEnum(2, mqType_);
    }
    if (port_ != 0) {
      output.writeInt32(3, port_);
    }
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, topic_);
    }
    if (!getAuthInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, authInfo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHostNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostName_);
    }
    if (mqType_ != org.opendedup.grpc.MessageQueue.MQType.RabbitMQ.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, mqType_);
    }
    if (port_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, port_);
    }
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, topic_);
    }
    if (!getAuthInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, authInfo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opendedup.grpc.MessageQueue)) {
      return super.equals(obj);
    }
    org.opendedup.grpc.MessageQueue other = (org.opendedup.grpc.MessageQueue) obj;

    if (!getHostName()
        .equals(other.getHostName())) return false;
    if (mqType_ != other.mqType_) return false;
    if (getPort()
        != other.getPort()) return false;
    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (!getAuthInfo()
        .equals(other.getAuthInfo())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostName().hashCode();
    hash = (37 * hash) + MQTYPE_FIELD_NUMBER;
    hash = (53 * hash) + mqType_;
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + getPort();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + AUTHINFO_FIELD_NUMBER;
    hash = (53 * hash) + getAuthInfo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opendedup.grpc.MessageQueue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.MessageQueue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.MessageQueue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.MessageQueue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.MessageQueue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.MessageQueue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.MessageQueue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.MessageQueue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opendedup.grpc.MessageQueue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.MessageQueue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opendedup.grpc.MessageQueue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.MessageQueue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opendedup.grpc.MessageQueue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opendedup.grpc.MessageQueue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opendedup.grpc.MessageQueue)
      org.opendedup.grpc.MessageQueueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_MessageQueue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_MessageQueue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opendedup.grpc.MessageQueue.class, org.opendedup.grpc.MessageQueue.Builder.class);
    }

    // Construct using org.opendedup.grpc.MessageQueue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hostName_ = "";

      mqType_ = 0;

      port_ = 0;

      topic_ = "";

      authInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opendedup.grpc.VolumeServiceOuterClass.internal_static_org_opendedup_grpc_MessageQueue_descriptor;
    }

    @java.lang.Override
    public org.opendedup.grpc.MessageQueue getDefaultInstanceForType() {
      return org.opendedup.grpc.MessageQueue.getDefaultInstance();
    }

    @java.lang.Override
    public org.opendedup.grpc.MessageQueue build() {
      org.opendedup.grpc.MessageQueue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opendedup.grpc.MessageQueue buildPartial() {
      org.opendedup.grpc.MessageQueue result = new org.opendedup.grpc.MessageQueue(this);
      result.hostName_ = hostName_;
      result.mqType_ = mqType_;
      result.port_ = port_;
      result.topic_ = topic_;
      result.authInfo_ = authInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opendedup.grpc.MessageQueue) {
        return mergeFrom((org.opendedup.grpc.MessageQueue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opendedup.grpc.MessageQueue other) {
      if (other == org.opendedup.grpc.MessageQueue.getDefaultInstance()) return this;
      if (!other.getHostName().isEmpty()) {
        hostName_ = other.hostName_;
        onChanged();
      }
      if (other.mqType_ != 0) {
        setMqTypeValue(other.getMqTypeValue());
      }
      if (other.getPort() != 0) {
        setPort(other.getPort());
      }
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getAuthInfo().isEmpty()) {
        authInfo_ = other.authInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.opendedup.grpc.MessageQueue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.opendedup.grpc.MessageQueue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object hostName_ = "";
    /**
     * <code>string hostName = 1;</code>
     * @return The hostName.
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostName = 1;</code>
     * @return The bytes for hostName.
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostName = 1;</code>
     * @param value The hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hostName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostName() {
      
      hostName_ = getDefaultInstance().getHostName();
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 1;</code>
     * @param value The bytes for hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hostName_ = value;
      onChanged();
      return this;
    }

    private int mqType_ = 0;
    /**
     * <code>.org.opendedup.grpc.MessageQueue.MQType mqType = 2;</code>
     * @return The enum numeric value on the wire for mqType.
     */
    @java.lang.Override public int getMqTypeValue() {
      return mqType_;
    }
    /**
     * <code>.org.opendedup.grpc.MessageQueue.MQType mqType = 2;</code>
     * @param value The enum numeric value on the wire for mqType to set.
     * @return This builder for chaining.
     */
    public Builder setMqTypeValue(int value) {
      
      mqType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.org.opendedup.grpc.MessageQueue.MQType mqType = 2;</code>
     * @return The mqType.
     */
    @java.lang.Override
    public org.opendedup.grpc.MessageQueue.MQType getMqType() {
      @SuppressWarnings("deprecation")
      org.opendedup.grpc.MessageQueue.MQType result = org.opendedup.grpc.MessageQueue.MQType.valueOf(mqType_);
      return result == null ? org.opendedup.grpc.MessageQueue.MQType.UNRECOGNIZED : result;
    }
    /**
     * <code>.org.opendedup.grpc.MessageQueue.MQType mqType = 2;</code>
     * @param value The mqType to set.
     * @return This builder for chaining.
     */
    public Builder setMqType(org.opendedup.grpc.MessageQueue.MQType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      mqType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.org.opendedup.grpc.MessageQueue.MQType mqType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMqType() {
      
      mqType_ = 0;
      onChanged();
      return this;
    }

    private int port_ ;
    /**
     * <code>int32 port = 3;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 3;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(int value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 port = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {
      
      port_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <code>string topic = 4;</code>
     * @return The topic.
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic = 4;</code>
     * @return The bytes for topic.
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic = 4;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 4;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object authInfo_ = "";
    /**
     * <code>string authInfo = 5;</code>
     * @return The authInfo.
     */
    public java.lang.String getAuthInfo() {
      java.lang.Object ref = authInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string authInfo = 5;</code>
     * @return The bytes for authInfo.
     */
    public com.google.protobuf.ByteString
        getAuthInfoBytes() {
      java.lang.Object ref = authInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string authInfo = 5;</code>
     * @param value The authInfo to set.
     * @return This builder for chaining.
     */
    public Builder setAuthInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string authInfo = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthInfo() {
      
      authInfo_ = getDefaultInstance().getAuthInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string authInfo = 5;</code>
     * @param value The bytes for authInfo to set.
     * @return This builder for chaining.
     */
    public Builder setAuthInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opendedup.grpc.MessageQueue)
  }

  // @@protoc_insertion_point(class_scope:org.opendedup.grpc.MessageQueue)
  private static final org.opendedup.grpc.MessageQueue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opendedup.grpc.MessageQueue();
  }

  public static org.opendedup.grpc.MessageQueue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageQueue>
      PARSER = new com.google.protobuf.AbstractParser<MessageQueue>() {
    @java.lang.Override
    public MessageQueue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageQueue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageQueue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageQueue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opendedup.grpc.MessageQueue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

