// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SDFSEvent.proto

package org.opendedup.grpc;

/**
 * Protobuf type {@code org.opendedup.grpc.SDFSEvent}
 */
public final class SDFSEvent extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:org.opendedup.grpc.SDFSEvent)
    SDFSEventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SDFSEvent.newBuilder() to construct.
  private SDFSEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SDFSEvent() {
    level_ = "";
    type_ = "";
    target_ = "";
    shortMsg_ = "";
    longMsg_ = "";
    uuid_ = "";
    parentUuid_ = "";
    extendedInfo_ = "";
    childrenUUid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SDFSEvent();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SDFSEvent(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            startTime_ = input.readInt64();
            break;
          }
          case 16: {

            endTime_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            level_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            target_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            shortMsg_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            longMsg_ = s;
            break;
          }
          case 65: {

            percentComplete_ = input.readDouble();
            break;
          }
          case 72: {

            maxCount_ = input.readInt64();
            break;
          }
          case 80: {

            currentCount_ = input.readInt64();
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            uuid_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            parentUuid_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            extendedInfo_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              childrenUUid_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            childrenUUid_.add(s);
            break;
          }
          case 120: {

            success_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        childrenUUid_ = childrenUUid_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.opendedup.grpc.SDFSEventOuterClass.internal_static_org_opendedup_grpc_SDFSEvent_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.opendedup.grpc.SDFSEventOuterClass.internal_static_org_opendedup_grpc_SDFSEvent_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.opendedup.grpc.SDFSEvent.class, org.opendedup.grpc.SDFSEvent.Builder.class);
  }

  public static final int STARTTIME_FIELD_NUMBER = 1;
  private long startTime_;
  /**
   * <code>int64 startTime = 1;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public long getStartTime() {
    return startTime_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 2;
  private long endTime_;
  /**
   * <code>int64 endTime = 2;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public long getEndTime() {
    return endTime_;
  }

  public static final int LEVEL_FIELD_NUMBER = 3;
  private volatile java.lang.Object level_;
  /**
   * <code>string level = 3;</code>
   * @return The level.
   */
  @java.lang.Override
  public java.lang.String getLevel() {
    java.lang.Object ref = level_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      level_ = s;
      return s;
    }
  }
  /**
   * <code>string level = 3;</code>
   * @return The bytes for level.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLevelBytes() {
    java.lang.Object ref = level_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      level_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TARGET_FIELD_NUMBER = 5;
  private volatile java.lang.Object target_;
  /**
   * <code>string target = 5;</code>
   * @return The target.
   */
  @java.lang.Override
  public java.lang.String getTarget() {
    java.lang.Object ref = target_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      target_ = s;
      return s;
    }
  }
  /**
   * <code>string target = 5;</code>
   * @return The bytes for target.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTargetBytes() {
    java.lang.Object ref = target_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      target_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHORTMSG_FIELD_NUMBER = 6;
  private volatile java.lang.Object shortMsg_;
  /**
   * <code>string shortMsg = 6;</code>
   * @return The shortMsg.
   */
  @java.lang.Override
  public java.lang.String getShortMsg() {
    java.lang.Object ref = shortMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      shortMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string shortMsg = 6;</code>
   * @return The bytes for shortMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getShortMsgBytes() {
    java.lang.Object ref = shortMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      shortMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LONGMSG_FIELD_NUMBER = 7;
  private volatile java.lang.Object longMsg_;
  /**
   * <code>string longMsg = 7;</code>
   * @return The longMsg.
   */
  @java.lang.Override
  public java.lang.String getLongMsg() {
    java.lang.Object ref = longMsg_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      longMsg_ = s;
      return s;
    }
  }
  /**
   * <code>string longMsg = 7;</code>
   * @return The bytes for longMsg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLongMsgBytes() {
    java.lang.Object ref = longMsg_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      longMsg_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PERCENTCOMPLETE_FIELD_NUMBER = 8;
  private double percentComplete_;
  /**
   * <code>double percentComplete = 8;</code>
   * @return The percentComplete.
   */
  @java.lang.Override
  public double getPercentComplete() {
    return percentComplete_;
  }

  public static final int MAXCOUNT_FIELD_NUMBER = 9;
  private long maxCount_;
  /**
   * <code>int64 maxCount = 9;</code>
   * @return The maxCount.
   */
  @java.lang.Override
  public long getMaxCount() {
    return maxCount_;
  }

  public static final int CURRENTCOUNT_FIELD_NUMBER = 10;
  private long currentCount_;
  /**
   * <code>int64 currentCount = 10;</code>
   * @return The currentCount.
   */
  @java.lang.Override
  public long getCurrentCount() {
    return currentCount_;
  }

  public static final int UUID_FIELD_NUMBER = 11;
  private volatile java.lang.Object uuid_;
  /**
   * <code>string uuid = 11;</code>
   * @return The uuid.
   */
  @java.lang.Override
  public java.lang.String getUuid() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uuid_ = s;
      return s;
    }
  }
  /**
   * <code>string uuid = 11;</code>
   * @return The bytes for uuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUuidBytes() {
    java.lang.Object ref = uuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARENTUUID_FIELD_NUMBER = 12;
  private volatile java.lang.Object parentUuid_;
  /**
   * <code>string parentUuid = 12;</code>
   * @return The parentUuid.
   */
  @java.lang.Override
  public java.lang.String getParentUuid() {
    java.lang.Object ref = parentUuid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      parentUuid_ = s;
      return s;
    }
  }
  /**
   * <code>string parentUuid = 12;</code>
   * @return The bytes for parentUuid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getParentUuidBytes() {
    java.lang.Object ref = parentUuid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      parentUuid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXTENDEDINFO_FIELD_NUMBER = 13;
  private volatile java.lang.Object extendedInfo_;
  /**
   * <code>string extendedInfo = 13;</code>
   * @return The extendedInfo.
   */
  @java.lang.Override
  public java.lang.String getExtendedInfo() {
    java.lang.Object ref = extendedInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      extendedInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string extendedInfo = 13;</code>
   * @return The bytes for extendedInfo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getExtendedInfoBytes() {
    java.lang.Object ref = extendedInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      extendedInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHILDRENUUID_FIELD_NUMBER = 14;
  private com.google.protobuf.LazyStringList childrenUUid_;
  /**
   * <code>repeated string childrenUUid = 14;</code>
   * @return A list containing the childrenUUid.
   */
  public com.google.protobuf.ProtocolStringList
      getChildrenUUidList() {
    return childrenUUid_;
  }
  /**
   * <code>repeated string childrenUUid = 14;</code>
   * @return The count of childrenUUid.
   */
  public int getChildrenUUidCount() {
    return childrenUUid_.size();
  }
  /**
   * <code>repeated string childrenUUid = 14;</code>
   * @param index The index of the element to return.
   * @return The childrenUUid at the given index.
   */
  public java.lang.String getChildrenUUid(int index) {
    return childrenUUid_.get(index);
  }
  /**
   * <code>repeated string childrenUUid = 14;</code>
   * @param index The index of the value to return.
   * @return The bytes of the childrenUUid at the given index.
   */
  public com.google.protobuf.ByteString
      getChildrenUUidBytes(int index) {
    return childrenUUid_.getByteString(index);
  }

  public static final int SUCCESS_FIELD_NUMBER = 15;
  private boolean success_;
  /**
   * <code>bool success = 15;</code>
   * @return The success.
   */
  @java.lang.Override
  public boolean getSuccess() {
    return success_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startTime_ != 0L) {
      output.writeInt64(1, startTime_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(2, endTime_);
    }
    if (!getLevelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, level_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
    }
    if (!getTargetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, target_);
    }
    if (!getShortMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, shortMsg_);
    }
    if (!getLongMsgBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, longMsg_);
    }
    if (percentComplete_ != 0D) {
      output.writeDouble(8, percentComplete_);
    }
    if (maxCount_ != 0L) {
      output.writeInt64(9, maxCount_);
    }
    if (currentCount_ != 0L) {
      output.writeInt64(10, currentCount_);
    }
    if (!getUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, uuid_);
    }
    if (!getParentUuidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, parentUuid_);
    }
    if (!getExtendedInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, extendedInfo_);
    }
    for (int i = 0; i < childrenUUid_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, childrenUUid_.getRaw(i));
    }
    if (success_ != false) {
      output.writeBool(15, success_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, startTime_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, endTime_);
    }
    if (!getLevelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, level_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
    }
    if (!getTargetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, target_);
    }
    if (!getShortMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, shortMsg_);
    }
    if (!getLongMsgBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, longMsg_);
    }
    if (percentComplete_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, percentComplete_);
    }
    if (maxCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, maxCount_);
    }
    if (currentCount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, currentCount_);
    }
    if (!getUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, uuid_);
    }
    if (!getParentUuidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, parentUuid_);
    }
    if (!getExtendedInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, extendedInfo_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < childrenUUid_.size(); i++) {
        dataSize += computeStringSizeNoTag(childrenUUid_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getChildrenUUidList().size();
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(15, success_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.opendedup.grpc.SDFSEvent)) {
      return super.equals(obj);
    }
    org.opendedup.grpc.SDFSEvent other = (org.opendedup.grpc.SDFSEvent) obj;

    if (getStartTime()
        != other.getStartTime()) return false;
    if (getEndTime()
        != other.getEndTime()) return false;
    if (!getLevel()
        .equals(other.getLevel())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getTarget()
        .equals(other.getTarget())) return false;
    if (!getShortMsg()
        .equals(other.getShortMsg())) return false;
    if (!getLongMsg()
        .equals(other.getLongMsg())) return false;
    if (java.lang.Double.doubleToLongBits(getPercentComplete())
        != java.lang.Double.doubleToLongBits(
            other.getPercentComplete())) return false;
    if (getMaxCount()
        != other.getMaxCount()) return false;
    if (getCurrentCount()
        != other.getCurrentCount()) return false;
    if (!getUuid()
        .equals(other.getUuid())) return false;
    if (!getParentUuid()
        .equals(other.getParentUuid())) return false;
    if (!getExtendedInfo()
        .equals(other.getExtendedInfo())) return false;
    if (!getChildrenUUidList()
        .equals(other.getChildrenUUidList())) return false;
    if (getSuccess()
        != other.getSuccess()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + getLevel().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + TARGET_FIELD_NUMBER;
    hash = (53 * hash) + getTarget().hashCode();
    hash = (37 * hash) + SHORTMSG_FIELD_NUMBER;
    hash = (53 * hash) + getShortMsg().hashCode();
    hash = (37 * hash) + LONGMSG_FIELD_NUMBER;
    hash = (53 * hash) + getLongMsg().hashCode();
    hash = (37 * hash) + PERCENTCOMPLETE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getPercentComplete()));
    hash = (37 * hash) + MAXCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMaxCount());
    hash = (37 * hash) + CURRENTCOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCurrentCount());
    hash = (37 * hash) + UUID_FIELD_NUMBER;
    hash = (53 * hash) + getUuid().hashCode();
    hash = (37 * hash) + PARENTUUID_FIELD_NUMBER;
    hash = (53 * hash) + getParentUuid().hashCode();
    hash = (37 * hash) + EXTENDEDINFO_FIELD_NUMBER;
    hash = (53 * hash) + getExtendedInfo().hashCode();
    if (getChildrenUUidCount() > 0) {
      hash = (37 * hash) + CHILDRENUUID_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenUUidList().hashCode();
    }
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.opendedup.grpc.SDFSEvent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.SDFSEvent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.SDFSEvent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.SDFSEvent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.SDFSEvent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.opendedup.grpc.SDFSEvent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.opendedup.grpc.SDFSEvent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.SDFSEvent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opendedup.grpc.SDFSEvent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.SDFSEvent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.opendedup.grpc.SDFSEvent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.opendedup.grpc.SDFSEvent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.opendedup.grpc.SDFSEvent prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code org.opendedup.grpc.SDFSEvent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:org.opendedup.grpc.SDFSEvent)
      org.opendedup.grpc.SDFSEventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.opendedup.grpc.SDFSEventOuterClass.internal_static_org_opendedup_grpc_SDFSEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.opendedup.grpc.SDFSEventOuterClass.internal_static_org_opendedup_grpc_SDFSEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.opendedup.grpc.SDFSEvent.class, org.opendedup.grpc.SDFSEvent.Builder.class);
    }

    // Construct using org.opendedup.grpc.SDFSEvent.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      startTime_ = 0L;

      endTime_ = 0L;

      level_ = "";

      type_ = "";

      target_ = "";

      shortMsg_ = "";

      longMsg_ = "";

      percentComplete_ = 0D;

      maxCount_ = 0L;

      currentCount_ = 0L;

      uuid_ = "";

      parentUuid_ = "";

      extendedInfo_ = "";

      childrenUUid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      success_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.opendedup.grpc.SDFSEventOuterClass.internal_static_org_opendedup_grpc_SDFSEvent_descriptor;
    }

    @java.lang.Override
    public org.opendedup.grpc.SDFSEvent getDefaultInstanceForType() {
      return org.opendedup.grpc.SDFSEvent.getDefaultInstance();
    }

    @java.lang.Override
    public org.opendedup.grpc.SDFSEvent build() {
      org.opendedup.grpc.SDFSEvent result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.opendedup.grpc.SDFSEvent buildPartial() {
      org.opendedup.grpc.SDFSEvent result = new org.opendedup.grpc.SDFSEvent(this);
      int from_bitField0_ = bitField0_;
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.level_ = level_;
      result.type_ = type_;
      result.target_ = target_;
      result.shortMsg_ = shortMsg_;
      result.longMsg_ = longMsg_;
      result.percentComplete_ = percentComplete_;
      result.maxCount_ = maxCount_;
      result.currentCount_ = currentCount_;
      result.uuid_ = uuid_;
      result.parentUuid_ = parentUuid_;
      result.extendedInfo_ = extendedInfo_;
      if (((bitField0_ & 0x00000001) != 0)) {
        childrenUUid_ = childrenUUid_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.childrenUUid_ = childrenUUid_;
      result.success_ = success_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.opendedup.grpc.SDFSEvent) {
        return mergeFrom((org.opendedup.grpc.SDFSEvent)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.opendedup.grpc.SDFSEvent other) {
      if (other == org.opendedup.grpc.SDFSEvent.getDefaultInstance()) return this;
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (!other.getLevel().isEmpty()) {
        level_ = other.level_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getTarget().isEmpty()) {
        target_ = other.target_;
        onChanged();
      }
      if (!other.getShortMsg().isEmpty()) {
        shortMsg_ = other.shortMsg_;
        onChanged();
      }
      if (!other.getLongMsg().isEmpty()) {
        longMsg_ = other.longMsg_;
        onChanged();
      }
      if (other.getPercentComplete() != 0D) {
        setPercentComplete(other.getPercentComplete());
      }
      if (other.getMaxCount() != 0L) {
        setMaxCount(other.getMaxCount());
      }
      if (other.getCurrentCount() != 0L) {
        setCurrentCount(other.getCurrentCount());
      }
      if (!other.getUuid().isEmpty()) {
        uuid_ = other.uuid_;
        onChanged();
      }
      if (!other.getParentUuid().isEmpty()) {
        parentUuid_ = other.parentUuid_;
        onChanged();
      }
      if (!other.getExtendedInfo().isEmpty()) {
        extendedInfo_ = other.extendedInfo_;
        onChanged();
      }
      if (!other.childrenUUid_.isEmpty()) {
        if (childrenUUid_.isEmpty()) {
          childrenUUid_ = other.childrenUUid_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureChildrenUUidIsMutable();
          childrenUUid_.addAll(other.childrenUUid_);
        }
        onChanged();
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.opendedup.grpc.SDFSEvent parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.opendedup.grpc.SDFSEvent) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long startTime_ ;
    /**
     * <code>int64 startTime = 1;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>int64 startTime = 1;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 startTime = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>int64 endTime = 2;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>int64 endTime = 2;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(long value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 endTime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object level_ = "";
    /**
     * <code>string level = 3;</code>
     * @return The level.
     */
    public java.lang.String getLevel() {
      java.lang.Object ref = level_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        level_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string level = 3;</code>
     * @return The bytes for level.
     */
    public com.google.protobuf.ByteString
        getLevelBytes() {
      java.lang.Object ref = level_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        level_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string level = 3;</code>
     * @param value The level to set.
     * @return This builder for chaining.
     */
    public Builder setLevel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      level_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string level = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLevel() {
      
      level_ = getDefaultInstance().getLevel();
      onChanged();
      return this;
    }
    /**
     * <code>string level = 3;</code>
     * @param value The bytes for level to set.
     * @return This builder for chaining.
     */
    public Builder setLevelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      level_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 4;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 4;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 4;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 4;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object target_ = "";
    /**
     * <code>string target = 5;</code>
     * @return The target.
     */
    public java.lang.String getTarget() {
      java.lang.Object ref = target_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        target_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string target = 5;</code>
     * @return The bytes for target.
     */
    public com.google.protobuf.ByteString
        getTargetBytes() {
      java.lang.Object ref = target_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        target_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string target = 5;</code>
     * @param value The target to set.
     * @return This builder for chaining.
     */
    public Builder setTarget(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      target_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string target = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTarget() {
      
      target_ = getDefaultInstance().getTarget();
      onChanged();
      return this;
    }
    /**
     * <code>string target = 5;</code>
     * @param value The bytes for target to set.
     * @return This builder for chaining.
     */
    public Builder setTargetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      target_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object shortMsg_ = "";
    /**
     * <code>string shortMsg = 6;</code>
     * @return The shortMsg.
     */
    public java.lang.String getShortMsg() {
      java.lang.Object ref = shortMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shortMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string shortMsg = 6;</code>
     * @return The bytes for shortMsg.
     */
    public com.google.protobuf.ByteString
        getShortMsgBytes() {
      java.lang.Object ref = shortMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shortMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string shortMsg = 6;</code>
     * @param value The shortMsg to set.
     * @return This builder for chaining.
     */
    public Builder setShortMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      shortMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string shortMsg = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearShortMsg() {
      
      shortMsg_ = getDefaultInstance().getShortMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string shortMsg = 6;</code>
     * @param value The bytes for shortMsg to set.
     * @return This builder for chaining.
     */
    public Builder setShortMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      shortMsg_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object longMsg_ = "";
    /**
     * <code>string longMsg = 7;</code>
     * @return The longMsg.
     */
    public java.lang.String getLongMsg() {
      java.lang.Object ref = longMsg_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        longMsg_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string longMsg = 7;</code>
     * @return The bytes for longMsg.
     */
    public com.google.protobuf.ByteString
        getLongMsgBytes() {
      java.lang.Object ref = longMsg_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        longMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string longMsg = 7;</code>
     * @param value The longMsg to set.
     * @return This builder for chaining.
     */
    public Builder setLongMsg(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      longMsg_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string longMsg = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLongMsg() {
      
      longMsg_ = getDefaultInstance().getLongMsg();
      onChanged();
      return this;
    }
    /**
     * <code>string longMsg = 7;</code>
     * @param value The bytes for longMsg to set.
     * @return This builder for chaining.
     */
    public Builder setLongMsgBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      longMsg_ = value;
      onChanged();
      return this;
    }

    private double percentComplete_ ;
    /**
     * <code>double percentComplete = 8;</code>
     * @return The percentComplete.
     */
    @java.lang.Override
    public double getPercentComplete() {
      return percentComplete_;
    }
    /**
     * <code>double percentComplete = 8;</code>
     * @param value The percentComplete to set.
     * @return This builder for chaining.
     */
    public Builder setPercentComplete(double value) {
      
      percentComplete_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double percentComplete = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPercentComplete() {
      
      percentComplete_ = 0D;
      onChanged();
      return this;
    }

    private long maxCount_ ;
    /**
     * <code>int64 maxCount = 9;</code>
     * @return The maxCount.
     */
    @java.lang.Override
    public long getMaxCount() {
      return maxCount_;
    }
    /**
     * <code>int64 maxCount = 9;</code>
     * @param value The maxCount to set.
     * @return This builder for chaining.
     */
    public Builder setMaxCount(long value) {
      
      maxCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 maxCount = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxCount() {
      
      maxCount_ = 0L;
      onChanged();
      return this;
    }

    private long currentCount_ ;
    /**
     * <code>int64 currentCount = 10;</code>
     * @return The currentCount.
     */
    @java.lang.Override
    public long getCurrentCount() {
      return currentCount_;
    }
    /**
     * <code>int64 currentCount = 10;</code>
     * @param value The currentCount to set.
     * @return This builder for chaining.
     */
    public Builder setCurrentCount(long value) {
      
      currentCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 currentCount = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrentCount() {
      
      currentCount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 11;</code>
     * @return The uuid.
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uuid = 11;</code>
     * @return The bytes for uuid.
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uuid = 11;</code>
     * @param value The uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      uuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearUuid() {
      
      uuid_ = getDefaultInstance().getUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string uuid = 11;</code>
     * @param value The bytes for uuid to set.
     * @return This builder for chaining.
     */
    public Builder setUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      uuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object parentUuid_ = "";
    /**
     * <code>string parentUuid = 12;</code>
     * @return The parentUuid.
     */
    public java.lang.String getParentUuid() {
      java.lang.Object ref = parentUuid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        parentUuid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string parentUuid = 12;</code>
     * @return The bytes for parentUuid.
     */
    public com.google.protobuf.ByteString
        getParentUuidBytes() {
      java.lang.Object ref = parentUuid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        parentUuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string parentUuid = 12;</code>
     * @param value The parentUuid to set.
     * @return This builder for chaining.
     */
    public Builder setParentUuid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      parentUuid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string parentUuid = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearParentUuid() {
      
      parentUuid_ = getDefaultInstance().getParentUuid();
      onChanged();
      return this;
    }
    /**
     * <code>string parentUuid = 12;</code>
     * @param value The bytes for parentUuid to set.
     * @return This builder for chaining.
     */
    public Builder setParentUuidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      parentUuid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object extendedInfo_ = "";
    /**
     * <code>string extendedInfo = 13;</code>
     * @return The extendedInfo.
     */
    public java.lang.String getExtendedInfo() {
      java.lang.Object ref = extendedInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        extendedInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string extendedInfo = 13;</code>
     * @return The bytes for extendedInfo.
     */
    public com.google.protobuf.ByteString
        getExtendedInfoBytes() {
      java.lang.Object ref = extendedInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        extendedInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string extendedInfo = 13;</code>
     * @param value The extendedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setExtendedInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      extendedInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string extendedInfo = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearExtendedInfo() {
      
      extendedInfo_ = getDefaultInstance().getExtendedInfo();
      onChanged();
      return this;
    }
    /**
     * <code>string extendedInfo = 13;</code>
     * @param value The bytes for extendedInfo to set.
     * @return This builder for chaining.
     */
    public Builder setExtendedInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      extendedInfo_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList childrenUUid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureChildrenUUidIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        childrenUUid_ = new com.google.protobuf.LazyStringArrayList(childrenUUid_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string childrenUUid = 14;</code>
     * @return A list containing the childrenUUid.
     */
    public com.google.protobuf.ProtocolStringList
        getChildrenUUidList() {
      return childrenUUid_.getUnmodifiableView();
    }
    /**
     * <code>repeated string childrenUUid = 14;</code>
     * @return The count of childrenUUid.
     */
    public int getChildrenUUidCount() {
      return childrenUUid_.size();
    }
    /**
     * <code>repeated string childrenUUid = 14;</code>
     * @param index The index of the element to return.
     * @return The childrenUUid at the given index.
     */
    public java.lang.String getChildrenUUid(int index) {
      return childrenUUid_.get(index);
    }
    /**
     * <code>repeated string childrenUUid = 14;</code>
     * @param index The index of the value to return.
     * @return The bytes of the childrenUUid at the given index.
     */
    public com.google.protobuf.ByteString
        getChildrenUUidBytes(int index) {
      return childrenUUid_.getByteString(index);
    }
    /**
     * <code>repeated string childrenUUid = 14;</code>
     * @param index The index to set the value at.
     * @param value The childrenUUid to set.
     * @return This builder for chaining.
     */
    public Builder setChildrenUUid(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureChildrenUUidIsMutable();
      childrenUUid_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string childrenUUid = 14;</code>
     * @param value The childrenUUid to add.
     * @return This builder for chaining.
     */
    public Builder addChildrenUUid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureChildrenUUidIsMutable();
      childrenUUid_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string childrenUUid = 14;</code>
     * @param values The childrenUUid to add.
     * @return This builder for chaining.
     */
    public Builder addAllChildrenUUid(
        java.lang.Iterable<java.lang.String> values) {
      ensureChildrenUUidIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, childrenUUid_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string childrenUUid = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearChildrenUUid() {
      childrenUUid_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string childrenUUid = 14;</code>
     * @param value The bytes of the childrenUUid to add.
     * @return This builder for chaining.
     */
    public Builder addChildrenUUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureChildrenUUidIsMutable();
      childrenUUid_.add(value);
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <code>bool success = 15;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 15;</code>
     * @param value The success to set.
     * @return This builder for chaining.
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool success = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:org.opendedup.grpc.SDFSEvent)
  }

  // @@protoc_insertion_point(class_scope:org.opendedup.grpc.SDFSEvent)
  private static final org.opendedup.grpc.SDFSEvent DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.opendedup.grpc.SDFSEvent();
  }

  public static org.opendedup.grpc.SDFSEvent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SDFSEvent>
      PARSER = new com.google.protobuf.AbstractParser<SDFSEvent>() {
    @java.lang.Override
    public SDFSEvent parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SDFSEvent(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SDFSEvent> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SDFSEvent> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.opendedup.grpc.SDFSEvent getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

