// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOService.proto

package org.opendedup.grpc;

public interface SetUserMetaDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opendedup.grpc.SetUserMetaDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  java.util.List<org.opendedup.grpc.FileAttributes> 
      getFileAttributesList();
  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  org.opendedup.grpc.FileAttributes getFileAttributes(int index);
  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  int getFileAttributesCount();
  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  java.util.List<? extends org.opendedup.grpc.FileAttributesOrBuilder> 
      getFileAttributesOrBuilderList();
  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  org.opendedup.grpc.FileAttributesOrBuilder getFileAttributesOrBuilder(
      int index);

  /**
   * <code>string Path = 2;</code>
   * @return The path.
   */
  java.lang.String getPath();
  /**
   * <code>string Path = 2;</code>
   * @return The bytes for path.
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
