// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOService.proto

package org.opendedup.grpc;

public interface SetXAttrResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opendedup.grpc.SetXAttrResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string error = 1;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 1;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  /**
   * <code>.org.opendedup.grpc.errorCodes errorCode = 2;</code>
   * @return The enum numeric value on the wire for errorCode.
   */
  int getErrorCodeValue();
  /**
   * <code>.org.opendedup.grpc.errorCodes errorCode = 2;</code>
   * @return The errorCode.
   */
  org.opendedup.grpc.errorCodes getErrorCode();

  /**
   * <code>.org.opendedup.grpc.SetXAttrResponse.flagsenum flags = 3;</code>
   * @return The enum numeric value on the wire for flags.
   */
  int getFlagsValue();
  /**
   * <code>.org.opendedup.grpc.SetXAttrResponse.flagsenum flags = 3;</code>
   * @return The flags.
   */
  org.opendedup.grpc.SetXAttrResponse.flagsenum getFlags();
}
