// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IOService.proto

package org.opendedup.grpc;

public interface StatFSRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opendedup.grpc.StatFSRequest)
    com.google.protobuf.MessageOrBuilder {
}
