// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: VolumeService.proto

package org.opendedup.grpc;

public interface SyncVolRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opendedup.grpc.SyncVolRequest)
    com.google.protobuf.MessageOrBuilder {
}
