// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FileInfo.proto

package org.opendedup.grpc;

public interface WFileAttributesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.opendedup.grpc.WFileAttributesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  java.util.List<org.opendedup.grpc.FileAttributes> 
      getFileAttributesList();
  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  org.opendedup.grpc.FileAttributes getFileAttributes(int index);
  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  int getFileAttributesCount();
  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  java.util.List<? extends org.opendedup.grpc.FileAttributesOrBuilder> 
      getFileAttributesOrBuilderList();
  /**
   * <code>repeated .org.opendedup.grpc.FileAttributes fileAttributes = 1;</code>
   */
  org.opendedup.grpc.FileAttributesOrBuilder getFileAttributesOrBuilder(
      int index);

  /**
   * <code>string filePath = 2;</code>
   * @return The filePath.
   */
  java.lang.String getFilePath();
  /**
   * <code>string filePath = 2;</code>
   * @return The bytes for filePath.
   */
  com.google.protobuf.ByteString
      getFilePathBytes();
}
