Document: sdfs
Title: Debian sdfs Manual
Author: <insert document author here>
Abstract: This manual describes what sdfs is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sdfs/sdfs.sgml.gz

Format: postscript
Files: /usr/share/doc/sdfs/sdfs.ps.gz

Format: text
Files: /usr/share/doc/sdfs/sdfs.text.gz

Format: HTML
Index: /usr/share/doc/sdfs/html/index.html
Files: /usr/share/doc/sdfs/html/*.html
