#!/bin/bash
#modprobe fuse > /dev/null
BASEMEMORY="3000"
CACHEMEMORY=512
MPTG=3
LMPTG=2
MU="M"
EXEC="/usr/share/sdfs/jsvc"
BASEPATH="/usr/share/sdfs"
PF="sdfs-ncfg.pid"
OPTIND=1
while getopts "v:z:f:p:e:anmzcdshcrlw" opt; do
  case $opt in
    v)
        echo "$OPTARG"
        CFG="/etc/sdfs/$OPTARG-volume-cfg.xml"
        PF="$OPTARG.pid"
        echo "Yahoo $CFG";;
    z)
      MEM=$OPTARG;;
    f)
        CFG=$OPTARG;;
    n) ;;
    w) ;;
    h) MEM=512
esac
done
if [ ! -n "$CFG" ]; then
        CFG="/etc/sdfs/$1-volume-cfg.xml"
        PF="$1.pid"
fi
if [ ! -n "$MEM" ]; then
if [ -n "$CFG" ] && [ -f "$CFG" ]; then
                th=$(echo 'cat //subsystem-config/io/@max-open-files' | xmllint --shell "$CFG" | grep -v ">" | cut -f 2 -d "=" | tr -d - | tr -d \");
                _wb=$(echo 'cat //subsystem-config/io/@max-file-write-buffers' | xmllint --shell "$CFG" | grep -v ">" | cut -f 2 -d "=" | tr -d - | tr -d \");
                if (( $_wb > 80 )); then
                        _wb=80;
                fi
                cm=$((((_wb*th))*2));
                MEMORY=$((BASEMEMORY+cm));
fi
else
        MEMORY=$MEM
fi

LD_PRELOAD="${BASEPATH}/bin/libfuse.so.2" $EXEC -server -outfile '&1' -errfile '&2' -Djava.library.path=${BASEPATH}/bin/ -home ${BASEPATH}/bin/jre -Dorg.apache.commons.logging.Log=fuse.logging.FuseLog -Xss2m \
 -wait 99999999999 -Dfuse.logging.level=INFO -Dfile.encoding=UTF-8 ${DOCKER_DETATCH} -Xmx$MEMORY$MU -Xms$MEMORY$MU \
-XX:+DisableExplicitGC -pidfile /var/run/$PF -XX:+UseG1GC -Djava.awt.headless=true \
 -cp ${BASEPATH}/lib/sdfs.jar:${BASEPATH}/lib/* fuse.SDFS.MountSDFS "$@"
